// <auto-generated>
/*
 * KakrLabs-SDK-Creator
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// BroadcastTransactiondto
    /// </summary>
    public partial class BroadcastTransactiondto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BroadcastTransactiondto" /> class.
        /// </summary>
        /// <param name="signedTxHash">signedTxHash</param>
        [JsonConstructor]
        public BroadcastTransactiondto(string signedTxHash)
        {
            SignedTxHash = signedTxHash;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets SignedTxHash
        /// </summary>
        [JsonPropertyName("signedTxHash")]
        public string SignedTxHash { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BroadcastTransactiondto {\n");
            sb.Append("  SignedTxHash: ").Append(SignedTxHash).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // SignedTxHash (string) minLength
            if (this.SignedTxHash != null && this.SignedTxHash.Length < 1)
            {
                yield return new ValidationResult("Invalid value for SignedTxHash, length must be greater than 1.", new [] { "SignedTxHash" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BroadcastTransactiondto" />
    /// </summary>
    public class BroadcastTransactiondtoJsonConverter : JsonConverter<BroadcastTransactiondto>
    {
        /// <summary>
        /// Deserializes json to <see cref="BroadcastTransactiondto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BroadcastTransactiondto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> signedTxHash = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "signedTxHash":
                            signedTxHash = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!signedTxHash.IsSet)
                throw new ArgumentException("Property is required for class BroadcastTransactiondto.", nameof(signedTxHash));

            if (signedTxHash.IsSet && signedTxHash.Value == null)
                throw new ArgumentNullException(nameof(signedTxHash), "Property is not nullable for class BroadcastTransactiondto.");

            return new BroadcastTransactiondto(signedTxHash.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="BroadcastTransactiondto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="broadcastTransactiondto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BroadcastTransactiondto broadcastTransactiondto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, broadcastTransactiondto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BroadcastTransactiondto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="broadcastTransactiondto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BroadcastTransactiondto broadcastTransactiondto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (broadcastTransactiondto.SignedTxHash == null)
                throw new ArgumentNullException(nameof(broadcastTransactiondto.SignedTxHash), "Property is required for class BroadcastTransactiondto.");

            writer.WriteString("signedTxHash", broadcastTransactiondto.SignedTxHash);
        }
    }
}
