// <auto-generated>
/*
 * KakrLabs-SDK-Creator
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CreateRawTransactiondtoV2
    /// </summary>
    public partial class CreateRawTransactiondtoV2 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateRawTransactiondtoV2" /> class.
        /// </summary>
        /// <param name="senderAddress">senderAddress</param>
        /// <param name="recipientAddress">recipientAddress</param>
        /// <param name="amount">amount</param>
        /// <param name="utxos">utxos</param>
        /// <param name="voutsN">voutsN</param>
        [JsonConstructor]
        public CreateRawTransactiondtoV2(string senderAddress, string recipientAddress, double amount, List<string> utxos, List<int> voutsN)
        {
            SenderAddress = senderAddress;
            RecipientAddress = recipientAddress;
            Amount = amount;
            Utxos = utxos;
            VoutsN = voutsN;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets SenderAddress
        /// </summary>
        [JsonPropertyName("senderAddress")]
        public string SenderAddress { get; set; }

        /// <summary>
        /// Gets or Sets RecipientAddress
        /// </summary>
        [JsonPropertyName("recipientAddress")]
        public string RecipientAddress { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [JsonPropertyName("amount")]
        public double Amount { get; set; }

        /// <summary>
        /// Gets or Sets Utxos
        /// </summary>
        [JsonPropertyName("utxos")]
        public List<string> Utxos { get; set; }

        /// <summary>
        /// Gets or Sets VoutsN
        /// </summary>
        [JsonPropertyName("vouts_n")]
        public List<int> VoutsN { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateRawTransactiondtoV2 {\n");
            sb.Append("  SenderAddress: ").Append(SenderAddress).Append("\n");
            sb.Append("  RecipientAddress: ").Append(RecipientAddress).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Utxos: ").Append(Utxos).Append("\n");
            sb.Append("  VoutsN: ").Append(VoutsN).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // SenderAddress (string) minLength
            if (this.SenderAddress != null && this.SenderAddress.Length < 1)
            {
                yield return new ValidationResult("Invalid value for SenderAddress, length must be greater than 1.", new [] { "SenderAddress" });
            }

            // RecipientAddress (string) minLength
            if (this.RecipientAddress != null && this.RecipientAddress.Length < 1)
            {
                yield return new ValidationResult("Invalid value for RecipientAddress, length must be greater than 1.", new [] { "RecipientAddress" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateRawTransactiondtoV2" />
    /// </summary>
    public class CreateRawTransactiondtoV2JsonConverter : JsonConverter<CreateRawTransactiondtoV2>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateRawTransactiondtoV2" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateRawTransactiondtoV2 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> senderAddress = default;
            Option<string?> recipientAddress = default;
            Option<double?> amount = default;
            Option<List<string>?> utxos = default;
            Option<List<int>?> voutsN = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "senderAddress":
                            senderAddress = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "recipientAddress":
                            recipientAddress = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "amount":
                            amount = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "utxos":
                            utxos = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "vouts_n":
                            voutsN = new Option<List<int>?>(JsonSerializer.Deserialize<List<int>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!senderAddress.IsSet)
                throw new ArgumentException("Property is required for class CreateRawTransactiondtoV2.", nameof(senderAddress));

            if (!recipientAddress.IsSet)
                throw new ArgumentException("Property is required for class CreateRawTransactiondtoV2.", nameof(recipientAddress));

            if (!amount.IsSet)
                throw new ArgumentException("Property is required for class CreateRawTransactiondtoV2.", nameof(amount));

            if (!utxos.IsSet)
                throw new ArgumentException("Property is required for class CreateRawTransactiondtoV2.", nameof(utxos));

            if (!voutsN.IsSet)
                throw new ArgumentException("Property is required for class CreateRawTransactiondtoV2.", nameof(voutsN));

            if (senderAddress.IsSet && senderAddress.Value == null)
                throw new ArgumentNullException(nameof(senderAddress), "Property is not nullable for class CreateRawTransactiondtoV2.");

            if (recipientAddress.IsSet && recipientAddress.Value == null)
                throw new ArgumentNullException(nameof(recipientAddress), "Property is not nullable for class CreateRawTransactiondtoV2.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class CreateRawTransactiondtoV2.");

            if (utxos.IsSet && utxos.Value == null)
                throw new ArgumentNullException(nameof(utxos), "Property is not nullable for class CreateRawTransactiondtoV2.");

            if (voutsN.IsSet && voutsN.Value == null)
                throw new ArgumentNullException(nameof(voutsN), "Property is not nullable for class CreateRawTransactiondtoV2.");

            return new CreateRawTransactiondtoV2(senderAddress.Value!, recipientAddress.Value!, amount.Value!.Value!, utxos.Value!, voutsN.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="CreateRawTransactiondtoV2" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createRawTransactiondtoV2"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateRawTransactiondtoV2 createRawTransactiondtoV2, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createRawTransactiondtoV2, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateRawTransactiondtoV2" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createRawTransactiondtoV2"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateRawTransactiondtoV2 createRawTransactiondtoV2, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createRawTransactiondtoV2.SenderAddress == null)
                throw new ArgumentNullException(nameof(createRawTransactiondtoV2.SenderAddress), "Property is required for class CreateRawTransactiondtoV2.");

            if (createRawTransactiondtoV2.RecipientAddress == null)
                throw new ArgumentNullException(nameof(createRawTransactiondtoV2.RecipientAddress), "Property is required for class CreateRawTransactiondtoV2.");

            if (createRawTransactiondtoV2.Utxos == null)
                throw new ArgumentNullException(nameof(createRawTransactiondtoV2.Utxos), "Property is required for class CreateRawTransactiondtoV2.");

            if (createRawTransactiondtoV2.VoutsN == null)
                throw new ArgumentNullException(nameof(createRawTransactiondtoV2.VoutsN), "Property is required for class CreateRawTransactiondtoV2.");

            writer.WriteString("senderAddress", createRawTransactiondtoV2.SenderAddress);

            writer.WriteString("recipientAddress", createRawTransactiondtoV2.RecipientAddress);

            writer.WriteNumber("amount", createRawTransactiondtoV2.Amount);

            writer.WritePropertyName("utxos");
            JsonSerializer.Serialize(writer, createRawTransactiondtoV2.Utxos, jsonSerializerOptions);
            writer.WritePropertyName("vouts_n");
            JsonSerializer.Serialize(writer, createRawTransactiondtoV2.VoutsN, jsonSerializerOptions);
        }
    }
}
