// <auto-generated>
/*
 * KakrLabs-SDK-Creator
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SignRawTransactiondto
    /// </summary>
    public partial class SignRawTransactiondto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SignRawTransactiondto" /> class.
        /// </summary>
        /// <param name="walletName">walletName</param>
        /// <param name="addressPrivateKey">addressPrivateKey</param>
        /// <param name="txhash">txhash</param>
        [JsonConstructor]
        public SignRawTransactiondto(string walletName, string addressPrivateKey, string txhash)
        {
            WalletName = walletName;
            AddressPrivateKey = addressPrivateKey;
            Txhash = txhash;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets WalletName
        /// </summary>
        [JsonPropertyName("walletName")]
        public string WalletName { get; set; }

        /// <summary>
        /// Gets or Sets AddressPrivateKey
        /// </summary>
        [JsonPropertyName("addressPrivateKey")]
        public string AddressPrivateKey { get; set; }

        /// <summary>
        /// Gets or Sets Txhash
        /// </summary>
        [JsonPropertyName("txhash")]
        public string Txhash { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SignRawTransactiondto {\n");
            sb.Append("  WalletName: ").Append(WalletName).Append("\n");
            sb.Append("  AddressPrivateKey: ").Append(AddressPrivateKey).Append("\n");
            sb.Append("  Txhash: ").Append(Txhash).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // WalletName (string) minLength
            if (this.WalletName != null && this.WalletName.Length < 1)
            {
                yield return new ValidationResult("Invalid value for WalletName, length must be greater than 1.", new [] { "WalletName" });
            }

            // AddressPrivateKey (string) minLength
            if (this.AddressPrivateKey != null && this.AddressPrivateKey.Length < 1)
            {
                yield return new ValidationResult("Invalid value for AddressPrivateKey, length must be greater than 1.", new [] { "AddressPrivateKey" });
            }

            // Txhash (string) minLength
            if (this.Txhash != null && this.Txhash.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Txhash, length must be greater than 1.", new [] { "Txhash" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SignRawTransactiondto" />
    /// </summary>
    public class SignRawTransactiondtoJsonConverter : JsonConverter<SignRawTransactiondto>
    {
        /// <summary>
        /// Deserializes json to <see cref="SignRawTransactiondto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SignRawTransactiondto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> walletName = default;
            Option<string?> addressPrivateKey = default;
            Option<string?> txhash = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "walletName":
                            walletName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "addressPrivateKey":
                            addressPrivateKey = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "txhash":
                            txhash = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!walletName.IsSet)
                throw new ArgumentException("Property is required for class SignRawTransactiondto.", nameof(walletName));

            if (!addressPrivateKey.IsSet)
                throw new ArgumentException("Property is required for class SignRawTransactiondto.", nameof(addressPrivateKey));

            if (!txhash.IsSet)
                throw new ArgumentException("Property is required for class SignRawTransactiondto.", nameof(txhash));

            if (walletName.IsSet && walletName.Value == null)
                throw new ArgumentNullException(nameof(walletName), "Property is not nullable for class SignRawTransactiondto.");

            if (addressPrivateKey.IsSet && addressPrivateKey.Value == null)
                throw new ArgumentNullException(nameof(addressPrivateKey), "Property is not nullable for class SignRawTransactiondto.");

            if (txhash.IsSet && txhash.Value == null)
                throw new ArgumentNullException(nameof(txhash), "Property is not nullable for class SignRawTransactiondto.");

            return new SignRawTransactiondto(walletName.Value!, addressPrivateKey.Value!, txhash.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="SignRawTransactiondto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="signRawTransactiondto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SignRawTransactiondto signRawTransactiondto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, signRawTransactiondto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SignRawTransactiondto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="signRawTransactiondto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SignRawTransactiondto signRawTransactiondto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (signRawTransactiondto.WalletName == null)
                throw new ArgumentNullException(nameof(signRawTransactiondto.WalletName), "Property is required for class SignRawTransactiondto.");

            if (signRawTransactiondto.AddressPrivateKey == null)
                throw new ArgumentNullException(nameof(signRawTransactiondto.AddressPrivateKey), "Property is required for class SignRawTransactiondto.");

            if (signRawTransactiondto.Txhash == null)
                throw new ArgumentNullException(nameof(signRawTransactiondto.Txhash), "Property is required for class SignRawTransactiondto.");

            writer.WriteString("walletName", signRawTransactiondto.WalletName);

            writer.WriteString("addressPrivateKey", signRawTransactiondto.AddressPrivateKey);

            writer.WriteString("txhash", signRawTransactiondto.Txhash);
        }
    }
}
