/*
KakrLabs-SDK-Creator

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateRawTransactiondto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRawTransactiondto{}

// CreateRawTransactiondto struct for CreateRawTransactiondto
type CreateRawTransactiondto struct {
	RecipientAddress string `json:"recipientAddress"`
	SenderAddress string `json:"senderAddress"`
	Amount float64 `json:"amount"`
}

type _CreateRawTransactiondto CreateRawTransactiondto

// NewCreateRawTransactiondto instantiates a new CreateRawTransactiondto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRawTransactiondto(recipientAddress string, senderAddress string, amount float64) *CreateRawTransactiondto {
	this := CreateRawTransactiondto{}
	this.RecipientAddress = recipientAddress
	this.SenderAddress = senderAddress
	this.Amount = amount
	return &this
}

// NewCreateRawTransactiondtoWithDefaults instantiates a new CreateRawTransactiondto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRawTransactiondtoWithDefaults() *CreateRawTransactiondto {
	this := CreateRawTransactiondto{}
	return &this
}

// GetRecipientAddress returns the RecipientAddress field value
func (o *CreateRawTransactiondto) GetRecipientAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RecipientAddress
}

// GetRecipientAddressOk returns a tuple with the RecipientAddress field value
// and a boolean to check if the value has been set.
func (o *CreateRawTransactiondto) GetRecipientAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecipientAddress, true
}

// SetRecipientAddress sets field value
func (o *CreateRawTransactiondto) SetRecipientAddress(v string) {
	o.RecipientAddress = v
}

// GetSenderAddress returns the SenderAddress field value
func (o *CreateRawTransactiondto) GetSenderAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SenderAddress
}

// GetSenderAddressOk returns a tuple with the SenderAddress field value
// and a boolean to check if the value has been set.
func (o *CreateRawTransactiondto) GetSenderAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SenderAddress, true
}

// SetSenderAddress sets field value
func (o *CreateRawTransactiondto) SetSenderAddress(v string) {
	o.SenderAddress = v
}

// GetAmount returns the Amount field value
func (o *CreateRawTransactiondto) GetAmount() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *CreateRawTransactiondto) GetAmountOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *CreateRawTransactiondto) SetAmount(v float64) {
	o.Amount = v
}

func (o CreateRawTransactiondto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRawTransactiondto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["recipientAddress"] = o.RecipientAddress
	toSerialize["senderAddress"] = o.SenderAddress
	toSerialize["amount"] = o.Amount
	return toSerialize, nil
}

func (o *CreateRawTransactiondto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"recipientAddress",
		"senderAddress",
		"amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateRawTransactiondto := _CreateRawTransactiondto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateRawTransactiondto)

	if err != nil {
		return err
	}

	*o = CreateRawTransactiondto(varCreateRawTransactiondto)

	return err
}

type NullableCreateRawTransactiondto struct {
	value *CreateRawTransactiondto
	isSet bool
}

func (v NullableCreateRawTransactiondto) Get() *CreateRawTransactiondto {
	return v.value
}

func (v *NullableCreateRawTransactiondto) Set(val *CreateRawTransactiondto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRawTransactiondto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRawTransactiondto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRawTransactiondto(val *CreateRawTransactiondto) *NullableCreateRawTransactiondto {
	return &NullableCreateRawTransactiondto{value: val, isSet: true}
}

func (v NullableCreateRawTransactiondto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRawTransactiondto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


