/*
 * KakrLabs-SDK-Creator
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SendFromWalletdto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SendFromWalletdtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SendFromWalletdto
        //private SendFromWalletdto instance;

        public SendFromWalletdtoTests()
        {
            // TODO uncomment below to create an instance of SendFromWalletdto
            //instance = new SendFromWalletdto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SendFromWalletdto
        /// </summary>
        [Fact]
        public void SendFromWalletdtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" SendFromWalletdto
            //Assert.IsType<SendFromWalletdto>(instance);
        }

        /// <summary>
        /// Test the property 'RecipientAddress'
        /// </summary>
        [Fact]
        public void RecipientAddressTest()
        {
            // TODO unit test for the property 'RecipientAddress'
        }

        /// <summary>
        /// Test the property 'RecipientName'
        /// </summary>
        [Fact]
        public void RecipientNameTest()
        {
            // TODO unit test for the property 'RecipientName'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'AmountIncludeFees'
        /// </summary>
        [Fact]
        public void AmountIncludeFeesTest()
        {
            // TODO unit test for the property 'AmountIncludeFees'
        }
    }
}
