/*
 * KakrLabs-SDK-Creator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ChangePassphrasedto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-28T20:52:14.094532800+01:00[Africa/Lagos]", comments = "Generator version: 7.14.0")
public class ChangePassphrasedto {
  public static final String SERIALIZED_NAME_WALLET = "wallet";
  @SerializedName(SERIALIZED_NAME_WALLET)
  @javax.annotation.Nonnull
  private String wallet;

  public static final String SERIALIZED_NAME_OLD_PASSPHRASE = "old_passphrase";
  @SerializedName(SERIALIZED_NAME_OLD_PASSPHRASE)
  @javax.annotation.Nonnull
  private String oldPassphrase;

  public static final String SERIALIZED_NAME_NEW_PASSPHRASE = "new_passphrase";
  @SerializedName(SERIALIZED_NAME_NEW_PASSPHRASE)
  @javax.annotation.Nonnull
  private String newPassphrase;

  public ChangePassphrasedto() {
  }

  public ChangePassphrasedto wallet(@javax.annotation.Nonnull String wallet) {
    this.wallet = wallet;
    return this;
  }

  /**
   * Get wallet
   * @return wallet
   */
  @javax.annotation.Nonnull
  public String getWallet() {
    return wallet;
  }

  public void setWallet(@javax.annotation.Nonnull String wallet) {
    this.wallet = wallet;
  }


  public ChangePassphrasedto oldPassphrase(@javax.annotation.Nonnull String oldPassphrase) {
    this.oldPassphrase = oldPassphrase;
    return this;
  }

  /**
   * Get oldPassphrase
   * @return oldPassphrase
   */
  @javax.annotation.Nonnull
  public String getOldPassphrase() {
    return oldPassphrase;
  }

  public void setOldPassphrase(@javax.annotation.Nonnull String oldPassphrase) {
    this.oldPassphrase = oldPassphrase;
  }


  public ChangePassphrasedto newPassphrase(@javax.annotation.Nonnull String newPassphrase) {
    this.newPassphrase = newPassphrase;
    return this;
  }

  /**
   * Get newPassphrase
   * @return newPassphrase
   */
  @javax.annotation.Nonnull
  public String getNewPassphrase() {
    return newPassphrase;
  }

  public void setNewPassphrase(@javax.annotation.Nonnull String newPassphrase) {
    this.newPassphrase = newPassphrase;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangePassphrasedto changePassphrasedto = (ChangePassphrasedto) o;
    return Objects.equals(this.wallet, changePassphrasedto.wallet) &&
        Objects.equals(this.oldPassphrase, changePassphrasedto.oldPassphrase) &&
        Objects.equals(this.newPassphrase, changePassphrasedto.newPassphrase);
  }

  @Override
  public int hashCode() {
    return Objects.hash(wallet, oldPassphrase, newPassphrase);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangePassphrasedto {\n");
    sb.append("    wallet: ").append(toIndentedString(wallet)).append("\n");
    sb.append("    oldPassphrase: ").append(toIndentedString(oldPassphrase)).append("\n");
    sb.append("    newPassphrase: ").append(toIndentedString(newPassphrase)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("wallet", "old_passphrase", "new_passphrase"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("wallet", "old_passphrase", "new_passphrase"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ChangePassphrasedto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ChangePassphrasedto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ChangePassphrasedto is not found in the empty JSON string", ChangePassphrasedto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ChangePassphrasedto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ChangePassphrasedto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ChangePassphrasedto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("wallet").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `wallet` to be a primitive type in the JSON string but got `%s`", jsonObj.get("wallet").toString()));
      }
      if (!jsonObj.get("old_passphrase").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `old_passphrase` to be a primitive type in the JSON string but got `%s`", jsonObj.get("old_passphrase").toString()));
      }
      if (!jsonObj.get("new_passphrase").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `new_passphrase` to be a primitive type in the JSON string but got `%s`", jsonObj.get("new_passphrase").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ChangePassphrasedto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ChangePassphrasedto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ChangePassphrasedto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ChangePassphrasedto.class));

       return (TypeAdapter<T>) new TypeAdapter<ChangePassphrasedto>() {
           @Override
           public void write(JsonWriter out, ChangePassphrasedto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ChangePassphrasedto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ChangePassphrasedto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ChangePassphrasedto
   * @throws IOException if the JSON string is invalid with respect to ChangePassphrasedto
   */
  public static ChangePassphrasedto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ChangePassphrasedto.class);
  }

  /**
   * Convert an instance of ChangePassphrasedto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

