/*
 * KakrLabs-SDK-Creator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CreateMultiSignatureAddressdto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-28T20:52:14.094532800+01:00[Africa/Lagos]", comments = "Generator version: 7.14.0")
public class CreateMultiSignatureAddressdto {
  public static final String SERIALIZED_NAME_ADDRESSES = "addresses";
  @SerializedName(SERIALIZED_NAME_ADDRESSES)
  @javax.annotation.Nonnull
  private String addresses;

  public static final String SERIALIZED_NAME_NREQIRED = "nreqired";
  @SerializedName(SERIALIZED_NAME_NREQIRED)
  @javax.annotation.Nonnull
  private Integer nreqired;

  public static final String SERIALIZED_NAME_ADDRESS_TYPE = "address_type";
  @SerializedName(SERIALIZED_NAME_ADDRESS_TYPE)
  @javax.annotation.Nonnull
  private String addressType;

  public CreateMultiSignatureAddressdto() {
  }

  public CreateMultiSignatureAddressdto addresses(@javax.annotation.Nonnull String addresses) {
    this.addresses = addresses;
    return this;
  }

  /**
   * addresses (L addresses) to be given priviledge to sign a transaction seperated with a comma for example LTm0jfypM0....Yi, Lkfr5tt......Mn
   * @return addresses
   */
  @javax.annotation.Nonnull
  public String getAddresses() {
    return addresses;
  }

  public void setAddresses(@javax.annotation.Nonnull String addresses) {
    this.addresses = addresses;
  }


  public CreateMultiSignatureAddressdto nreqired(@javax.annotation.Nonnull Integer nreqired) {
    this.nreqired = nreqired;
    return this;
  }

  /**
   * Get nreqired
   * @return nreqired
   */
  @javax.annotation.Nonnull
  public Integer getNreqired() {
    return nreqired;
  }

  public void setNreqired(@javax.annotation.Nonnull Integer nreqired) {
    this.nreqired = nreqired;
  }


  public CreateMultiSignatureAddressdto addressType(@javax.annotation.Nonnull String addressType) {
    this.addressType = addressType;
    return this;
  }

  /**
   * Get addressType
   * @return addressType
   */
  @javax.annotation.Nonnull
  public String getAddressType() {
    return addressType;
  }

  public void setAddressType(@javax.annotation.Nonnull String addressType) {
    this.addressType = addressType;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateMultiSignatureAddressdto createMultiSignatureAddressdto = (CreateMultiSignatureAddressdto) o;
    return Objects.equals(this.addresses, createMultiSignatureAddressdto.addresses) &&
        Objects.equals(this.nreqired, createMultiSignatureAddressdto.nreqired) &&
        Objects.equals(this.addressType, createMultiSignatureAddressdto.addressType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addresses, nreqired, addressType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateMultiSignatureAddressdto {\n");
    sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
    sb.append("    nreqired: ").append(toIndentedString(nreqired)).append("\n");
    sb.append("    addressType: ").append(toIndentedString(addressType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("addresses", "nreqired", "address_type"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("addresses", "nreqired", "address_type"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateMultiSignatureAddressdto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateMultiSignatureAddressdto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateMultiSignatureAddressdto is not found in the empty JSON string", CreateMultiSignatureAddressdto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateMultiSignatureAddressdto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateMultiSignatureAddressdto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateMultiSignatureAddressdto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("addresses").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `addresses` to be a primitive type in the JSON string but got `%s`", jsonObj.get("addresses").toString()));
      }
      if (!jsonObj.get("address_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `address_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("address_type").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateMultiSignatureAddressdto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateMultiSignatureAddressdto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateMultiSignatureAddressdto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateMultiSignatureAddressdto.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateMultiSignatureAddressdto>() {
           @Override
           public void write(JsonWriter out, CreateMultiSignatureAddressdto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateMultiSignatureAddressdto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateMultiSignatureAddressdto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateMultiSignatureAddressdto
   * @throws IOException if the JSON string is invalid with respect to CreateMultiSignatureAddressdto
   */
  public static CreateMultiSignatureAddressdto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateMultiSignatureAddressdto.class);
  }

  /**
   * Convert an instance of CreateMultiSignatureAddressdto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

