/*
 * KakrLabs-SDK-Creator
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangePassphrasedto {
    #[serde(rename = "wallet")]
    pub wallet: String,
    #[serde(rename = "old_passphrase")]
    pub old_passphrase: String,
    #[serde(rename = "new_passphrase")]
    pub new_passphrase: String,
}

impl ChangePassphrasedto {
    pub fn new(wallet: String, old_passphrase: String, new_passphrase: String) -> ChangePassphrasedto {
        ChangePassphrasedto {
            wallet,
            old_passphrase,
            new_passphrase,
        }
    }
}

