/*
 * KakrLabs-SDK-Creator
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRawTransactiondtoV3 {
    #[serde(rename = "senderAddress")]
    pub sender_address: String,
    #[serde(rename = "serviceFeeAddress")]
    pub service_fee_address: String,
    #[serde(rename = "recipientAddress")]
    pub recipient_address: String,
    #[serde(rename = "serviceFeeAmount")]
    pub service_fee_amount: f32,
    #[serde(rename = "amount")]
    pub amount: f32,
}

impl CreateRawTransactiondtoV3 {
    pub fn new(sender_address: String, service_fee_address: String, recipient_address: String, service_fee_amount: f32, amount: f32) -> CreateRawTransactiondtoV3 {
        CreateRawTransactiondtoV3 {
            sender_address,
            service_fee_address,
            recipient_address,
            service_fee_amount,
            amount,
        }
    }
}

