/*
 * KakrLabs-SDK-Creator
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignMessagedto {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "addressPrivatKey")]
    pub address_privat_key: String,
}

impl SignMessagedto {
    pub fn new(message: String, address_privat_key: String) -> SignMessagedto {
        SignMessagedto {
            message,
            address_privat_key,
        }
    }
}

