/*
 * KakrLabs-SDK-Creator
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyOtPdto {
    #[serde(rename = "signtaure")]
    pub signtaure: String,
    #[serde(rename = "code")]
    pub code: String,
}

impl VerifyOtPdto {
    pub fn new(signtaure: String, code: String) -> VerifyOtPdto {
        VerifyOtPdto {
            signtaure,
            code,
        }
    }
}

