=begin
#KakrLabs-SDK-Creator

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'cgi'

module OpenapiClient
  class TransactionsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # broadcast transaction on the Litecoin blockchain
    # @param [Hash] opts the optional parameters
    # @option opts [String] :node_url_or_api_access_key 
    # @option opts [BroadcastTransactiondto] :broadcast_transactiondto 
    # @return [nil]
    def api_transactions_broadcast_transaction_post(opts = {})
      api_transactions_broadcast_transaction_post_with_http_info(opts)
      nil
    end

    # broadcast transaction on the Litecoin blockchain
    # @param [Hash] opts the optional parameters
    # @option opts [String] :node_url_or_api_access_key 
    # @option opts [BroadcastTransactiondto] :broadcast_transactiondto 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_transactions_broadcast_transaction_post_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TransactionsApi.api_transactions_broadcast_transaction_post ...'
      end
      # resource path
      local_var_path = '/api/Transactions/broadcast-transaction'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'text/json', 'application/*+json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'nodeUrlOrApiAccessKey'] = opts[:'node_url_or_api_access_key'] if !opts[:'node_url_or_api_access_key'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'broadcast_transactiondto'])

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"TransactionsApi.api_transactions_broadcast_transaction_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TransactionsApi#api_transactions_broadcast_transaction_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # create raw transaction - returns the transaction hash
    # @param [Hash] opts the optional parameters
    # @option opts [String] :node_url_or_api_access_key 
    # @option opts [String] :wallet_name 
    # @option opts [CreateRawTransactiondto] :create_raw_transactiondto 
    # @return [nil]
    def api_transactions_create_raw_transaction_post(opts = {})
      api_transactions_create_raw_transaction_post_with_http_info(opts)
      nil
    end

    # create raw transaction - returns the transaction hash
    # @param [Hash] opts the optional parameters
    # @option opts [String] :node_url_or_api_access_key 
    # @option opts [String] :wallet_name 
    # @option opts [CreateRawTransactiondto] :create_raw_transactiondto 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_transactions_create_raw_transaction_post_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TransactionsApi.api_transactions_create_raw_transaction_post ...'
      end
      # resource path
      local_var_path = '/api/Transactions/create-raw-transaction'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'text/json', 'application/*+json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'nodeUrlOrApiAccessKey'] = opts[:'node_url_or_api_access_key'] if !opts[:'node_url_or_api_access_key'].nil?
      header_params[:'walletName'] = opts[:'wallet_name'] if !opts[:'wallet_name'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'create_raw_transactiondto'])

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"TransactionsApi.api_transactions_create_raw_transaction_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TransactionsApi#api_transactions_create_raw_transaction_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # create raw transaction with the address UTXOs - returns the transaction hash
    # @param [Hash] opts the optional parameters
    # @option opts [String] :node_url_or_api_access_key 
    # @option opts [CreateRawTransactiondtoV2] :create_raw_transactiondto_v2 
    # @return [nil]
    def api_transactions_create_raw_transaction_v2_post(opts = {})
      api_transactions_create_raw_transaction_v2_post_with_http_info(opts)
      nil
    end

    # create raw transaction with the address UTXOs - returns the transaction hash
    # @param [Hash] opts the optional parameters
    # @option opts [String] :node_url_or_api_access_key 
    # @option opts [CreateRawTransactiondtoV2] :create_raw_transactiondto_v2 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_transactions_create_raw_transaction_v2_post_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TransactionsApi.api_transactions_create_raw_transaction_v2_post ...'
      end
      # resource path
      local_var_path = '/api/Transactions/create-raw-transaction-v2'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'text/json', 'application/*+json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'nodeUrlOrApiAccessKey'] = opts[:'node_url_or_api_access_key'] if !opts[:'node_url_or_api_access_key'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'create_raw_transactiondto_v2'])

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"TransactionsApi.api_transactions_create_raw_transaction_v2_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TransactionsApi#api_transactions_create_raw_transaction_v2_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # create raw transaction with the service Fee address attached - returns the transaction hash
    # @param [Hash] opts the optional parameters
    # @option opts [String] :node_url_or_api_access_key 
    # @option opts [String] :wallet_name 
    # @option opts [CreateRawTransactiondtoV3] :create_raw_transactiondto_v3 
    # @return [nil]
    def api_transactions_create_raw_transaction_v3_post(opts = {})
      api_transactions_create_raw_transaction_v3_post_with_http_info(opts)
      nil
    end

    # create raw transaction with the service Fee address attached - returns the transaction hash
    # @param [Hash] opts the optional parameters
    # @option opts [String] :node_url_or_api_access_key 
    # @option opts [String] :wallet_name 
    # @option opts [CreateRawTransactiondtoV3] :create_raw_transactiondto_v3 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_transactions_create_raw_transaction_v3_post_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TransactionsApi.api_transactions_create_raw_transaction_v3_post ...'
      end
      # resource path
      local_var_path = '/api/Transactions/create-raw-transaction-v3'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'text/json', 'application/*+json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'nodeUrlOrApiAccessKey'] = opts[:'node_url_or_api_access_key'] if !opts[:'node_url_or_api_access_key'].nil?
      header_params[:'walletName'] = opts[:'wallet_name'] if !opts[:'wallet_name'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'create_raw_transactiondto_v3'])

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"TransactionsApi.api_transactions_create_raw_transaction_v3_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TransactionsApi#api_transactions_create_raw_transaction_v3_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Send a funds from one address to another using wallet
    # @param [Hash] opts the optional parameters
    # @option opts [String] :node_url_or_api_access_key 
    # @option opts [String] :wallet_name 
    # @option opts [String] :encrypted_passphrase 
    # @option opts [SendFromWalletdto] :send_from_walletdto 
    # @return [nil]
    def api_transactions_send_funds_from_wallet_post(opts = {})
      api_transactions_send_funds_from_wallet_post_with_http_info(opts)
      nil
    end

    # Send a funds from one address to another using wallet
    # @param [Hash] opts the optional parameters
    # @option opts [String] :node_url_or_api_access_key 
    # @option opts [String] :wallet_name 
    # @option opts [String] :encrypted_passphrase 
    # @option opts [SendFromWalletdto] :send_from_walletdto 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_transactions_send_funds_from_wallet_post_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TransactionsApi.api_transactions_send_funds_from_wallet_post ...'
      end
      # resource path
      local_var_path = '/api/Transactions/send-funds-from-wallet'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'text/json', 'application/*+json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'nodeUrlOrApiAccessKey'] = opts[:'node_url_or_api_access_key'] if !opts[:'node_url_or_api_access_key'].nil?
      header_params[:'walletName'] = opts[:'wallet_name'] if !opts[:'wallet_name'].nil?
      header_params[:'encryptedPassphrase'] = opts[:'encrypted_passphrase'] if !opts[:'encrypted_passphrase'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'send_from_walletdto'])

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"TransactionsApi.api_transactions_send_funds_from_wallet_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TransactionsApi#api_transactions_send_funds_from_wallet_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # sign a created raw transaction - returns the signed transaction hash
    # @param [Hash] opts the optional parameters
    # @option opts [String] :node_url_or_api_access_key 
    # @option opts [String] :wallet_name 
    # @option opts [SignRawTransactiondto] :sign_raw_transactiondto 
    # @return [nil]
    def api_transactions_sign_transaction_post(opts = {})
      api_transactions_sign_transaction_post_with_http_info(opts)
      nil
    end

    # sign a created raw transaction - returns the signed transaction hash
    # @param [Hash] opts the optional parameters
    # @option opts [String] :node_url_or_api_access_key 
    # @option opts [String] :wallet_name 
    # @option opts [SignRawTransactiondto] :sign_raw_transactiondto 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_transactions_sign_transaction_post_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TransactionsApi.api_transactions_sign_transaction_post ...'
      end
      # resource path
      local_var_path = '/api/Transactions/sign-transaction'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'text/json', 'application/*+json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'nodeUrlOrApiAccessKey'] = opts[:'node_url_or_api_access_key'] if !opts[:'node_url_or_api_access_key'].nil?
      header_params[:'walletName'] = opts[:'wallet_name'] if !opts[:'wallet_name'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'sign_raw_transactiondto'])

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"TransactionsApi.api_transactions_sign_transaction_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TransactionsApi#api_transactions_sign_transaction_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
