=begin
#KakrLabs-SDK-Creator

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::UtilitiesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UtilitiesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::UtilitiesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UtilitiesApi' do
    it 'should create an instance of UtilitiesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::UtilitiesApi)
    end
  end

  # unit tests for api_utilities_get_blockchain_otp_get
  # Gets OTP using the blockchain information using the signature of a signed message.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :node_url_or_api_access_key 
  # @option opts [String] :signature 
  # @return [nil]
  describe 'api_utilities_get_blockchain_otp_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_utilities_verify_otp_post
  # Verifies the OTP on the blockchain.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :node_url_or_api_access_key 
  # @option opts [VerifyOTPdto] :verify_ot_pdto 
  # @return [nil]
  describe 'api_utilities_verify_otp_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
