/**
 * KakrLabs-SDK-Creator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BroadcastTransactiondto model module.
 * @module model/BroadcastTransactiondto
 * @version 1.0
 */
class BroadcastTransactiondto {
    /**
     * Constructs a new <code>BroadcastTransactiondto</code>.
     * @alias module:model/BroadcastTransactiondto
     * @param signedTxHash {String} 
     */
    constructor(signedTxHash) { 
        
        BroadcastTransactiondto.initialize(this, signedTxHash);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, signedTxHash) { 
        obj['signedTxHash'] = signedTxHash;
    }

    /**
     * Constructs a <code>BroadcastTransactiondto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BroadcastTransactiondto} obj Optional instance to populate.
     * @return {module:model/BroadcastTransactiondto} The populated <code>BroadcastTransactiondto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BroadcastTransactiondto();

            if (data.hasOwnProperty('signedTxHash')) {
                obj['signedTxHash'] = ApiClient.convertToType(data['signedTxHash'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BroadcastTransactiondto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BroadcastTransactiondto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BroadcastTransactiondto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['signedTxHash'] && !(typeof data['signedTxHash'] === 'string' || data['signedTxHash'] instanceof String)) {
            throw new Error("Expected the field `signedTxHash` to be a primitive type in the JSON string but got " + data['signedTxHash']);
        }

        return true;
    }


}

BroadcastTransactiondto.RequiredProperties = ["signedTxHash"];

/**
 * @member {String} signedTxHash
 */
BroadcastTransactiondto.prototype['signedTxHash'] = undefined;






export default BroadcastTransactiondto;

