/**
 * KakrLabs-SDK-Creator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateRawTransactiondtoV3 model module.
 * @module model/CreateRawTransactiondtoV3
 * @version 1.0
 */
class CreateRawTransactiondtoV3 {
    /**
     * Constructs a new <code>CreateRawTransactiondtoV3</code>.
     * @alias module:model/CreateRawTransactiondtoV3
     * @param senderAddress {String} 
     * @param serviceFeeAddress {String} 
     * @param recipientAddress {String} 
     * @param serviceFeeAmount {Number} 
     * @param amount {Number} 
     */
    constructor(senderAddress, serviceFeeAddress, recipientAddress, serviceFeeAmount, amount) { 
        
        CreateRawTransactiondtoV3.initialize(this, senderAddress, serviceFeeAddress, recipientAddress, serviceFeeAmount, amount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, senderAddress, serviceFeeAddress, recipientAddress, serviceFeeAmount, amount) { 
        obj['senderAddress'] = senderAddress;
        obj['serviceFeeAddress'] = serviceFeeAddress;
        obj['recipientAddress'] = recipientAddress;
        obj['serviceFeeAmount'] = serviceFeeAmount;
        obj['amount'] = amount;
    }

    /**
     * Constructs a <code>CreateRawTransactiondtoV3</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateRawTransactiondtoV3} obj Optional instance to populate.
     * @return {module:model/CreateRawTransactiondtoV3} The populated <code>CreateRawTransactiondtoV3</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateRawTransactiondtoV3();

            if (data.hasOwnProperty('senderAddress')) {
                obj['senderAddress'] = ApiClient.convertToType(data['senderAddress'], 'String');
            }
            if (data.hasOwnProperty('serviceFeeAddress')) {
                obj['serviceFeeAddress'] = ApiClient.convertToType(data['serviceFeeAddress'], 'String');
            }
            if (data.hasOwnProperty('recipientAddress')) {
                obj['recipientAddress'] = ApiClient.convertToType(data['recipientAddress'], 'String');
            }
            if (data.hasOwnProperty('serviceFeeAmount')) {
                obj['serviceFeeAmount'] = ApiClient.convertToType(data['serviceFeeAmount'], 'Number');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateRawTransactiondtoV3</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateRawTransactiondtoV3</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateRawTransactiondtoV3.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['senderAddress'] && !(typeof data['senderAddress'] === 'string' || data['senderAddress'] instanceof String)) {
            throw new Error("Expected the field `senderAddress` to be a primitive type in the JSON string but got " + data['senderAddress']);
        }
        // ensure the json data is a string
        if (data['serviceFeeAddress'] && !(typeof data['serviceFeeAddress'] === 'string' || data['serviceFeeAddress'] instanceof String)) {
            throw new Error("Expected the field `serviceFeeAddress` to be a primitive type in the JSON string but got " + data['serviceFeeAddress']);
        }
        // ensure the json data is a string
        if (data['recipientAddress'] && !(typeof data['recipientAddress'] === 'string' || data['recipientAddress'] instanceof String)) {
            throw new Error("Expected the field `recipientAddress` to be a primitive type in the JSON string but got " + data['recipientAddress']);
        }

        return true;
    }


}

CreateRawTransactiondtoV3.RequiredProperties = ["senderAddress", "serviceFeeAddress", "recipientAddress", "serviceFeeAmount", "amount"];

/**
 * @member {String} senderAddress
 */
CreateRawTransactiondtoV3.prototype['senderAddress'] = undefined;

/**
 * @member {String} serviceFeeAddress
 */
CreateRawTransactiondtoV3.prototype['serviceFeeAddress'] = undefined;

/**
 * @member {String} recipientAddress
 */
CreateRawTransactiondtoV3.prototype['recipientAddress'] = undefined;

/**
 * @member {Number} serviceFeeAmount
 */
CreateRawTransactiondtoV3.prototype['serviceFeeAmount'] = undefined;

/**
 * @member {Number} amount
 */
CreateRawTransactiondtoV3.prototype['amount'] = undefined;






export default CreateRawTransactiondtoV3;

