/**
 * KakrLabs-SDK-Creator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateRawTransactiondto model module.
 * @module model/CreateRawTransactiondto
 * @version 1.0
 */
class CreateRawTransactiondto {
    /**
     * Constructs a new <code>CreateRawTransactiondto</code>.
     * @alias module:model/CreateRawTransactiondto
     * @param recipientAddress {String} 
     * @param senderAddress {String} 
     * @param amount {Number} 
     */
    constructor(recipientAddress, senderAddress, amount) { 
        
        CreateRawTransactiondto.initialize(this, recipientAddress, senderAddress, amount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, recipientAddress, senderAddress, amount) { 
        obj['recipientAddress'] = recipientAddress;
        obj['senderAddress'] = senderAddress;
        obj['amount'] = amount;
    }

    /**
     * Constructs a <code>CreateRawTransactiondto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateRawTransactiondto} obj Optional instance to populate.
     * @return {module:model/CreateRawTransactiondto} The populated <code>CreateRawTransactiondto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateRawTransactiondto();

            if (data.hasOwnProperty('recipientAddress')) {
                obj['recipientAddress'] = ApiClient.convertToType(data['recipientAddress'], 'String');
            }
            if (data.hasOwnProperty('senderAddress')) {
                obj['senderAddress'] = ApiClient.convertToType(data['senderAddress'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateRawTransactiondto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateRawTransactiondto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateRawTransactiondto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['recipientAddress'] && !(typeof data['recipientAddress'] === 'string' || data['recipientAddress'] instanceof String)) {
            throw new Error("Expected the field `recipientAddress` to be a primitive type in the JSON string but got " + data['recipientAddress']);
        }
        // ensure the json data is a string
        if (data['senderAddress'] && !(typeof data['senderAddress'] === 'string' || data['senderAddress'] instanceof String)) {
            throw new Error("Expected the field `senderAddress` to be a primitive type in the JSON string but got " + data['senderAddress']);
        }

        return true;
    }


}

CreateRawTransactiondto.RequiredProperties = ["recipientAddress", "senderAddress", "amount"];

/**
 * @member {String} recipientAddress
 */
CreateRawTransactiondto.prototype['recipientAddress'] = undefined;

/**
 * @member {String} senderAddress
 */
CreateRawTransactiondto.prototype['senderAddress'] = undefined;

/**
 * @member {Number} amount
 */
CreateRawTransactiondto.prototype['amount'] = undefined;






export default CreateRawTransactiondto;

