/**
 * KakrLabs-SDK-Creator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SendFromWalletdto model module.
 * @module model/SendFromWalletdto
 * @version 1.0
 */
class SendFromWalletdto {
    /**
     * Constructs a new <code>SendFromWalletdto</code>.
     * @alias module:model/SendFromWalletdto
     */
    constructor() { 
        
        SendFromWalletdto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SendFromWalletdto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendFromWalletdto} obj Optional instance to populate.
     * @return {module:model/SendFromWalletdto} The populated <code>SendFromWalletdto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendFromWalletdto();

            if (data.hasOwnProperty('recipientAddress')) {
                obj['recipientAddress'] = ApiClient.convertToType(data['recipientAddress'], 'String');
            }
            if (data.hasOwnProperty('recipientName')) {
                obj['recipientName'] = ApiClient.convertToType(data['recipientName'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('amountIncludeFees')) {
                obj['amountIncludeFees'] = ApiClient.convertToType(data['amountIncludeFees'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SendFromWalletdto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SendFromWalletdto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['recipientAddress'] && !(typeof data['recipientAddress'] === 'string' || data['recipientAddress'] instanceof String)) {
            throw new Error("Expected the field `recipientAddress` to be a primitive type in the JSON string but got " + data['recipientAddress']);
        }
        // ensure the json data is a string
        if (data['recipientName'] && !(typeof data['recipientName'] === 'string' || data['recipientName'] instanceof String)) {
            throw new Error("Expected the field `recipientName` to be a primitive type in the JSON string but got " + data['recipientName']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}



/**
 * @member {String} recipientAddress
 */
SendFromWalletdto.prototype['recipientAddress'] = undefined;

/**
 * @member {String} recipientName
 */
SendFromWalletdto.prototype['recipientName'] = undefined;

/**
 * @member {Number} amount
 */
SendFromWalletdto.prototype['amount'] = undefined;

/**
 * @member {String} description
 */
SendFromWalletdto.prototype['description'] = undefined;

/**
 * @member {Boolean} amountIncludeFees
 */
SendFromWalletdto.prototype['amountIncludeFees'] = undefined;






export default SendFromWalletdto;

