/**
 * KakrLabs-SDK-Creator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SetWalletMnemonicsdto model module.
 * @module model/SetWalletMnemonicsdto
 * @version 1.0
 */
class SetWalletMnemonicsdto {
    /**
     * Constructs a new <code>SetWalletMnemonicsdto</code>.
     * @alias module:model/SetWalletMnemonicsdto
     * @param mnemonics {String} The mnemonics to set for the wallet.
     */
    constructor(mnemonics) { 
        
        SetWalletMnemonicsdto.initialize(this, mnemonics);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, mnemonics) { 
        obj['mnemonics'] = mnemonics;
    }

    /**
     * Constructs a <code>SetWalletMnemonicsdto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SetWalletMnemonicsdto} obj Optional instance to populate.
     * @return {module:model/SetWalletMnemonicsdto} The populated <code>SetWalletMnemonicsdto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SetWalletMnemonicsdto();

            if (data.hasOwnProperty('mnemonics')) {
                obj['mnemonics'] = ApiClient.convertToType(data['mnemonics'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SetWalletMnemonicsdto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SetWalletMnemonicsdto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SetWalletMnemonicsdto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['mnemonics'] && !(typeof data['mnemonics'] === 'string' || data['mnemonics'] instanceof String)) {
            throw new Error("Expected the field `mnemonics` to be a primitive type in the JSON string but got " + data['mnemonics']);
        }

        return true;
    }


}

SetWalletMnemonicsdto.RequiredProperties = ["mnemonics"];

/**
 * The mnemonics to set for the wallet.
 * @member {String} mnemonics
 */
SetWalletMnemonicsdto.prototype['mnemonics'] = undefined;






export default SetWalletMnemonicsdto;

