/**
 * KakrLabs-SDK-Creator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SignRawTransactiondto model module.
 * @module model/SignRawTransactiondto
 * @version 1.0
 */
class SignRawTransactiondto {
    /**
     * Constructs a new <code>SignRawTransactiondto</code>.
     * @alias module:model/SignRawTransactiondto
     * @param walletName {String} 
     * @param addressPrivateKey {String} 
     * @param txhash {String} 
     */
    constructor(walletName, addressPrivateKey, txhash) { 
        
        SignRawTransactiondto.initialize(this, walletName, addressPrivateKey, txhash);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, walletName, addressPrivateKey, txhash) { 
        obj['walletName'] = walletName;
        obj['addressPrivateKey'] = addressPrivateKey;
        obj['txhash'] = txhash;
    }

    /**
     * Constructs a <code>SignRawTransactiondto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SignRawTransactiondto} obj Optional instance to populate.
     * @return {module:model/SignRawTransactiondto} The populated <code>SignRawTransactiondto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SignRawTransactiondto();

            if (data.hasOwnProperty('walletName')) {
                obj['walletName'] = ApiClient.convertToType(data['walletName'], 'String');
            }
            if (data.hasOwnProperty('addressPrivateKey')) {
                obj['addressPrivateKey'] = ApiClient.convertToType(data['addressPrivateKey'], 'String');
            }
            if (data.hasOwnProperty('txhash')) {
                obj['txhash'] = ApiClient.convertToType(data['txhash'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SignRawTransactiondto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SignRawTransactiondto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SignRawTransactiondto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['walletName'] && !(typeof data['walletName'] === 'string' || data['walletName'] instanceof String)) {
            throw new Error("Expected the field `walletName` to be a primitive type in the JSON string but got " + data['walletName']);
        }
        // ensure the json data is a string
        if (data['addressPrivateKey'] && !(typeof data['addressPrivateKey'] === 'string' || data['addressPrivateKey'] instanceof String)) {
            throw new Error("Expected the field `addressPrivateKey` to be a primitive type in the JSON string but got " + data['addressPrivateKey']);
        }
        // ensure the json data is a string
        if (data['txhash'] && !(typeof data['txhash'] === 'string' || data['txhash'] instanceof String)) {
            throw new Error("Expected the field `txhash` to be a primitive type in the JSON string but got " + data['txhash']);
        }

        return true;
    }


}

SignRawTransactiondto.RequiredProperties = ["walletName", "addressPrivateKey", "txhash"];

/**
 * @member {String} walletName
 */
SignRawTransactiondto.prototype['walletName'] = undefined;

/**
 * @member {String} addressPrivateKey
 */
SignRawTransactiondto.prototype['addressPrivateKey'] = undefined;

/**
 * @member {String} txhash
 */
SignRawTransactiondto.prototype['txhash'] = undefined;






export default SignRawTransactiondto;

