/**
 * KakrLabs-SDK-Creator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SignMessagedto model module.
 * @module model/SignMessagedto
 * @version 1.0
 */
class SignMessagedto {
    /**
     * Constructs a new <code>SignMessagedto</code>.
     * @alias module:model/SignMessagedto
     * @param message {String} 
     * @param addressPrivatKey {String} 
     */
    constructor(message, addressPrivatKey) { 
        
        SignMessagedto.initialize(this, message, addressPrivatKey);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message, addressPrivatKey) { 
        obj['message'] = message;
        obj['addressPrivatKey'] = addressPrivatKey;
    }

    /**
     * Constructs a <code>SignMessagedto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SignMessagedto} obj Optional instance to populate.
     * @return {module:model/SignMessagedto} The populated <code>SignMessagedto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SignMessagedto();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('addressPrivatKey')) {
                obj['addressPrivatKey'] = ApiClient.convertToType(data['addressPrivatKey'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SignMessagedto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SignMessagedto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SignMessagedto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // ensure the json data is a string
        if (data['addressPrivatKey'] && !(typeof data['addressPrivatKey'] === 'string' || data['addressPrivatKey'] instanceof String)) {
            throw new Error("Expected the field `addressPrivatKey` to be a primitive type in the JSON string but got " + data['addressPrivatKey']);
        }

        return true;
    }


}

SignMessagedto.RequiredProperties = ["message", "addressPrivatKey"];

/**
 * @member {String} message
 */
SignMessagedto.prototype['message'] = undefined;

/**
 * @member {String} addressPrivatKey
 */
SignMessagedto.prototype['addressPrivatKey'] = undefined;






export default SignMessagedto;

