/* tslint:disable */
/* eslint-disable */
/**
 * KakrLabs-SDK-Creator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EncryptWalletDto
 */
export interface EncryptWalletDto {
    /**
     * 
     * @type {string}
     * @memberof EncryptWalletDto
     */
    passphrase: string;
}

/**
 * Check if a given object implements the EncryptWalletDto interface.
 */
export function instanceOfEncryptWalletDto(value: object): value is EncryptWalletDto {
    if (!('passphrase' in value) || value['passphrase'] === undefined) return false;
    return true;
}

export function EncryptWalletDtoFromJSON(json: any): EncryptWalletDto {
    return EncryptWalletDtoFromJSONTyped(json, false);
}

export function EncryptWalletDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncryptWalletDto {
    if (json == null) {
        return json;
    }
    return {
        
        'passphrase': json['passphrase'],
    };
}

export function EncryptWalletDtoToJSON(json: any): EncryptWalletDto {
    return EncryptWalletDtoToJSONTyped(json, false);
}

export function EncryptWalletDtoToJSONTyped(value?: EncryptWalletDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'passphrase': value['passphrase'],
    };
}

