/* tslint:disable */
/* eslint-disable */
/**
 * KakrLabs-SDK-Creator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImportWalletdto
 */
export interface ImportWalletdto {
    /**
     * 
     * @type {string}
     * @memberof ImportWalletdto
     */
    newWalletName: string;
    /**
     * 
     * @type {string}
     * @memberof ImportWalletdto
     */
    mnemonics: string;
}

/**
 * Check if a given object implements the ImportWalletdto interface.
 */
export function instanceOfImportWalletdto(value: object): value is ImportWalletdto {
    if (!('newWalletName' in value) || value['newWalletName'] === undefined) return false;
    if (!('mnemonics' in value) || value['mnemonics'] === undefined) return false;
    return true;
}

export function ImportWalletdtoFromJSON(json: any): ImportWalletdto {
    return ImportWalletdtoFromJSONTyped(json, false);
}

export function ImportWalletdtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportWalletdto {
    if (json == null) {
        return json;
    }
    return {
        
        'newWalletName': json['new_wallet_name'],
        'mnemonics': json['mnemonics'],
    };
}

export function ImportWalletdtoToJSON(json: any): ImportWalletdto {
    return ImportWalletdtoToJSONTyped(json, false);
}

export function ImportWalletdtoToJSONTyped(value?: ImportWalletdto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'new_wallet_name': value['newWalletName'],
        'mnemonics': value['mnemonics'],
    };
}

