/* tslint:disable */
/* eslint-disable */
/**
 * KakrLabs-SDK-Creator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendFromWalletdto
 */
export interface SendFromWalletdto {
    /**
     * 
     * @type {string}
     * @memberof SendFromWalletdto
     */
    recipientAddress?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SendFromWalletdto
     */
    recipientName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SendFromWalletdto
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof SendFromWalletdto
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SendFromWalletdto
     */
    amountIncludeFees?: boolean;
}

/**
 * Check if a given object implements the SendFromWalletdto interface.
 */
export function instanceOfSendFromWalletdto(value: object): value is SendFromWalletdto {
    return true;
}

export function SendFromWalletdtoFromJSON(json: any): SendFromWalletdto {
    return SendFromWalletdtoFromJSONTyped(json, false);
}

export function SendFromWalletdtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendFromWalletdto {
    if (json == null) {
        return json;
    }
    return {
        
        'recipientAddress': json['recipientAddress'] == null ? undefined : json['recipientAddress'],
        'recipientName': json['recipientName'] == null ? undefined : json['recipientName'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'description': json['description'] == null ? undefined : json['description'],
        'amountIncludeFees': json['amountIncludeFees'] == null ? undefined : json['amountIncludeFees'],
    };
}

export function SendFromWalletdtoToJSON(json: any): SendFromWalletdto {
    return SendFromWalletdtoToJSONTyped(json, false);
}

export function SendFromWalletdtoToJSONTyped(value?: SendFromWalletdto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recipientAddress': value['recipientAddress'],
        'recipientName': value['recipientName'],
        'amount': value['amount'],
        'description': value['description'],
        'amountIncludeFees': value['amountIncludeFees'],
    };
}

