/* tslint:disable */
/* eslint-disable */
/**
 * KakrLabs-SDK-Creator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyOTPdto
 */
export interface VerifyOTPdto {
    /**
     * 
     * @type {string}
     * @memberof VerifyOTPdto
     */
    signtaure: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyOTPdto
     */
    code: string;
}

/**
 * Check if a given object implements the VerifyOTPdto interface.
 */
export function instanceOfVerifyOTPdto(value: object): value is VerifyOTPdto {
    if (!('signtaure' in value) || value['signtaure'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function VerifyOTPdtoFromJSON(json: any): VerifyOTPdto {
    return VerifyOTPdtoFromJSONTyped(json, false);
}

export function VerifyOTPdtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyOTPdto {
    if (json == null) {
        return json;
    }
    return {
        
        'signtaure': json['signtaure'],
        'code': json['code'],
    };
}

export function VerifyOTPdtoToJSON(json: any): VerifyOTPdto {
    return VerifyOTPdtoToJSONTyped(json, false);
}

export function VerifyOTPdtoToJSONTyped(value?: VerifyOTPdto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signtaure': value['signtaure'],
        'code': value['code'],
    };
}

