/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param addresses addresses (L addresses) to be given priviledge to sign a transaction seperated with a comma for example LTm0jfypM0....Yi, Lkfr5tt......Mn
 * @param nreqired 
 * @param addressType 
 */


data class CreateMultiSignatureAddressdto (

    /* addresses (L addresses) to be given priviledge to sign a transaction seperated with a comma for example LTm0jfypM0....Yi, Lkfr5tt......Mn */
    @Json(name = "addresses")
    val addresses: kotlin.String,

    @Json(name = "nreqired")
    val nreqired: kotlin.Int,

    @Json(name = "address_type")
    val addressType: kotlin.String

) {


}

