/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param senderAddress 
 * @param serviceFeeAddress 
 * @param recipientAddress 
 * @param serviceFeeAmount 
 * @param amount 
 */


data class CreateRawTransactiondtoV3 (

    @Json(name = "senderAddress")
    val senderAddress: kotlin.String,

    @Json(name = "serviceFeeAddress")
    val serviceFeeAddress: kotlin.String,

    @Json(name = "recipientAddress")
    val recipientAddress: kotlin.String,

    @Json(name = "serviceFeeAmount")
    val serviceFeeAmount: kotlin.Float,

    @Json(name = "amount")
    val amount: kotlin.Float

) {


}

