/**
 * KakrLabs-SDK-Creator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KakrLabsSdkCreator);
  }
}(this, function(expect, KakrLabsSdkCreator) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KakrLabsSdkCreator.ChangePassphrasedto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ChangePassphrasedto', function() {
    it('should create an instance of ChangePassphrasedto', function() {
      // uncomment below and update the code to test ChangePassphrasedto
      //var instance = new KakrLabsSdkCreator.ChangePassphrasedto();
      //expect(instance).to.be.a(KakrLabsSdkCreator.ChangePassphrasedto);
    });

    it('should have the property wallet (base name: "wallet")', function() {
      // uncomment below and update the code to test the property wallet
      //var instance = new KakrLabsSdkCreator.ChangePassphrasedto();
      //expect(instance).to.be();
    });

    it('should have the property oldPassphrase (base name: "old_passphrase")', function() {
      // uncomment below and update the code to test the property oldPassphrase
      //var instance = new KakrLabsSdkCreator.ChangePassphrasedto();
      //expect(instance).to.be();
    });

    it('should have the property newPassphrase (base name: "new_passphrase")', function() {
      // uncomment below and update the code to test the property newPassphrase
      //var instance = new KakrLabsSdkCreator.ChangePassphrasedto();
      //expect(instance).to.be();
    });

  });

}));
