# coding: utf-8

"""
    KakrLabs-SDK-Creator

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.verify_messagedto import VerifyMessagedto

class TestVerifyMessagedto(unittest.TestCase):
    """VerifyMessagedto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VerifyMessagedto:
        """Test VerifyMessagedto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VerifyMessagedto`
        """
        model = VerifyMessagedto()
        if include_optional:
            return VerifyMessagedto(
                address = '0',
                message = '0',
                signature = '0'
            )
        else:
            return VerifyMessagedto(
                address = '0',
                message = '0',
                signature = '0',
        )
        """

    def testVerifyMessagedto(self):
        """Test VerifyMessagedto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
