# coding: utf-8

"""
    KakrLabs-SDK-Creator

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.wallet_api import WalletApi


class TestWalletApi(unittest.TestCase):
    """WalletApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WalletApi()

    def tearDown(self) -> None:
        pass

    def test_api_wallet_addresses_get(self) -> None:
        """Test case for api_wallet_addresses_get

        Get all addresses of a wallet.
        """
        pass

    def test_api_wallet_balance_get(self) -> None:
        """Test case for api_wallet_balance_get

        Get the balance of a wallet.
        """
        pass

    def test_api_wallet_change_passphrase_post(self) -> None:
        """Test case for api_wallet_change_passphrase_post

        Change the passphrase of a wallet.
        """
        pass

    def test_api_wallet_create_encrypted_wallet_post(self) -> None:
        """Test case for api_wallet_create_encrypted_wallet_post

        Create an encrypted wallet. this wallet created will be encrypted but cannot be imported to other wallets.
        """
        pass

    def test_api_wallet_create_importable_encrypted_wallet_post(self) -> None:
        """Test case for api_wallet_create_importable_encrypted_wallet_post

        Create an importable encrypted wallet. this wallet created will be encrypted and can be imported to other wallets.
        """
        pass

    def test_api_wallet_create_importable_wallet_post(self) -> None:
        """Test case for api_wallet_create_importable_wallet_post

        Create an importable wallet. this wallet created will be encrypted and can be imported to other wallets.
        """
        pass

    def test_api_wallet_create_post(self) -> None:
        """Test case for api_wallet_create_post

        Create a new wallet. this wallet created but not encrypted and cannot be imported to other wallets.
        """
        pass

    def test_api_wallet_details_get(self) -> None:
        """Test case for api_wallet_details_get

        Get the details of a wallet.
        """
        pass

    def test_api_wallet_encrypt_wallet_post(self) -> None:
        """Test case for api_wallet_encrypt_wallet_post

        Encrypt a wallet. this wallet created  cannot be imported to other wallets.
        """
        pass

    def test_api_wallet_import_wallet_post(self) -> None:
        """Test case for api_wallet_import_wallet_post

        Import a wallet. this wallet created will be encrypted and can be imported to other wallets.
        """
        pass

    def test_api_wallet_official_address_get(self) -> None:
        """Test case for api_wallet_official_address_get

        Get the official address of a wallet.
        """
        pass

    def test_api_wallet_set_wallet_mnemonics_post(self) -> None:
        """Test case for api_wallet_set_wallet_mnemonics_post

        Set the mnemonics of a wallet.
        """
        pass

    def test_api_wallet_sign_wallet_message_post(self) -> None:
        """Test case for api_wallet_sign_wallet_message_post

        Sign a message using the wallet.
        """
        pass

    def test_api_wallet_transactions_get(self) -> None:
        """Test case for api_wallet_transactions_get

        Get the transactions of a wallet.
        """
        pass

    def test_api_wallet_wallet_address_balance_get(self) -> None:
        """Test case for api_wallet_wallet_address_balance_get

        Get the balance of a specific address in a wallet.
        """
        pass

    def test_api_wallet_wallet_address_transactions_get(self) -> None:
        """Test case for api_wallet_wallet_address_transactions_get

        Get the transactions of a specific address in a wallet.
        """
        pass

    def test_api_wallet_wallet_default_address_get(self) -> None:
        """Test case for api_wallet_wallet_default_address_get

        default addresss of a wallet without private key
        """
        pass

    def test_api_wallet_wallet_default_address_v2_get(self) -> None:
        """Test case for api_wallet_wallet_default_address_v2_get

        default addresss of a wallet with private key
        """
        pass


if __name__ == '__main__':
    unittest.main()
