# coding: utf-8

"""
    KakrLabs-SDK-Creator

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.blocks_api import BlocksApi


class TestBlocksApi(unittest.TestCase):
    """BlocksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BlocksApi()

    def tearDown(self) -> None:
        pass

    def test_api_blocks_block_header_get(self) -> None:
        """Test case for api_blocks_block_header_get

        Get block header information
        """
        pass

    def test_api_blocks_block_stat_get(self) -> None:
        """Test case for api_blocks_block_stat_get

        Get block statistics
        """
        pass

    def test_api_blocks_block_transaction_get(self) -> None:
        """Test case for api_blocks_block_transaction_get

        Get block Transactions in details
        """
        pass

    def test_api_blocks_blockchain_info_get(self) -> None:
        """Test case for api_blocks_blockchain_info_get

        Get Litcoin Block information
        """
        pass


if __name__ == '__main__':
    unittest.main()
