# coding: utf-8

"""
    KakrLabs-SDK-Creator

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.send_from_walletdto import SendFromWalletdto

class TestSendFromWalletdto(unittest.TestCase):
    """SendFromWalletdto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendFromWalletdto:
        """Test SendFromWalletdto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendFromWalletdto`
        """
        model = SendFromWalletdto()
        if include_optional:
            return SendFromWalletdto(
                recipient_address = '',
                recipient_name = '',
                amount = 1.337,
                description = '',
                amount_include_fees = True
            )
        else:
            return SendFromWalletdto(
        )
        """

    def testSendFromWalletdto(self):
        """Test SendFromWalletdto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
