/**
 * KakrLabs-SDK-Creator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";

/**
* Litecoin service.
* @module api/LitecoinApi
* @version 1.0
*/
export default class LitecoinApi {

    /**
    * Constructs a new LitecoinApi. 
    * @alias module:api/LitecoinApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiLitecoinGetUtxoDetailsGet operation.
     * @callback module:api/LitecoinApi~apiLitecoinGetUtxoDetailsGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Litecoin UTXO details - returns the details of a UTXO using the transaction id and vout index
     * @param {Object} opts Optional parameters
     * @param {String} [nodeUrlOrApiAccessKey] 
     * @param {String} [txid] 
     * @param {Number} [voutN] 
     * @param {module:api/LitecoinApi~apiLitecoinGetUtxoDetailsGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiLitecoinGetUtxoDetailsGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'txid': opts['txid'],
        'vout_n': opts['voutN']
      };
      let headerParams = {
        'nodeUrlOrApiAccessKey': opts['nodeUrlOrApiAccessKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/Litecoin/get-utxo-details', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiLitecoinTransactionDetailsGet operation.
     * @callback module:api/LitecoinApi~apiLitecoinTransactionDetailsGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Litecoin transaction details - returns the full details of a transaction id
     * @param {Object} opts Optional parameters
     * @param {String} [nodeUrlOrApiAccessKey] 
     * @param {String} [txid] 
     * @param {module:api/LitecoinApi~apiLitecoinTransactionDetailsGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiLitecoinTransactionDetailsGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'txid': opts['txid']
      };
      let headerParams = {
        'nodeUrlOrApiAccessKey': opts['nodeUrlOrApiAccessKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/Litecoin/transaction-details', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
